add galaxybase cypher impl and query
ldbc/ldbc_finbench_transaction_impls pull request #21
Opened 2023-05-16 03:02 UTC by BingTong0

2023-05-26 06:50 UTC, qishipengqsp requested changes
需要个readme，包括如何获取包，怎么跑等等。

2023-05-26 06:50 UTC, qishipengqsp commented on galaxybase-cypher/pom.xml
为什么这里有个pom

2023-05-26 06:50 UTC, qishipengqsp commented on galaxybase-cypher/pom.xml
galaxybase和galaxybase-cypher是两个submodule？

2023-05-26 06:53 UTC, BingTong0 commented on galaxybase-cypher/pom.xml
readme 我后面一起加。 对的两个module, 之前那个是计划procedure做的，我可以先删掉

2023-06-07 04:03 UTC, qishipengqsp reviewed
proc的先删了吧啊

2023-06-07 04:37 UTC, BingTong0 commented on galaxybase-cypher/lib/graphdbapi-bolt-driver-3.5.0.jar
没有公开的源
proc我单独开个pr删，后期万一要做这个版本方便拉回

2023-06-08 04:46 UTC, merged